### PR TITLE
[#1521, #1417] Refactored data prep pipeline to use non-persisted fields

### LINKED ISSUE #1417: Ensure data field cleaning & validation on ActiveEffect changes supports goals.
The implementation of https://github.com/foundryvtt/foundryvtt/issues/9468 means that field constraints also apply to active effects. We should investigate if this can be extended & leveraged, as well use it for fields like Stability that should have a data-model enforced minimum of 0.

### LINKED ISSUE #1521: Implement non-persisted data fields
We should define and implement non-persisted data fields to help guide AE application.

See https://github.com/foundryvtt/foundryvtt/issues/13460

### LINKED ISSUE #1788: Ability Modifier disabled by Kit Melee Damage Bonus
### What happened?

I implemented an active effect as ability modifier with the following properties, no restrictions:

Image

However, as soon as a kit with any melee damage bonus (ranged damage bonus does not affect) is added, those properties seem to be ignored
Without damage bonus:
Image

With damage bonus:
Image

### Reproduction Steps

1. Add ability modifier (see above) to hero actor sheet
2. Add kit to actor sheet
3. Add any melee damage bonus to kit

### What core and system version are you reporting this for?
Core: v13 Stable 9 Build 351
System: 0.11.1

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled
- [x] I am using The Forge for hosting

### PR DESCRIPTION
**Pull request by JPMeehan**
Fairly major refactor of data prep pipeline but with a lot of clear benefits. 

Closes #1417
Closes #1521

### CODE REVIEW

File: src/module/data/actor/party.mjs [hunk 1]
```diff
@@ -79,6 +79,7 @@ export default class PartyModel extends DrawSteelSystemModel {
   prepareBaseData() {
     super.prepareBaseData();
 
+    // TODO: Consider making a bespoke field to handle this initialization transformation
```
Comment (krbz999) [inline src/module/data/actor/party.mjs:82]: The reason this is not done is because the party actor cannot know about deletions or other changes to the members. But a getter always retrieves current data.

File: src/module/data/pseudo-documents/power-roll-effects/forced-movement-effect.mjs [hunk 2]
```diff
@@ -1,34 +1,42 @@
...
+        setOptions(),
+        { initial: ["push"], label: "DRAW_STEEL.POWER_ROLL_EFFECT.FIELDS.movement.label" },
+      ),
+      distance: new FormulaField({ deterministic: true, initial: "1", label: "DRAW_STEEL.POWER_ROLL_EFFECT.FIELDS.distance.label" }),
+      properties: new SetField(setOptions(), { label: "DRAW_STEEL.POWER_ROLL_EFFECT.FIELDS.properties.label" }),
+    }));
+
+    forced.extendFields({
+
+      bonuses: new SchemaField({
```
Comment (krbz999) [inline src/module/data/pseudo-documents/power-roll-effects/forced-movement-effect.mjs:31]:
```suggestion
    forced.extendFields({
      bonuses: new SchemaField({
```

File: src/module/data/helpers.mjs [hunk 3]
```diff
@@ -7,9 +7,10 @@ const { NumberField, SchemaField, StringField } = foundry.data.fields;
  * @param {number} [options.min=0]      The minimum value for the field.
  * @param {number} [options.max]        The maximum value for the field.
  * @param {string} [options.label]      Label for the field.
+ * @param {boolean} [options.persisted] Is the field saved to the database?
  * @returns A number field that is non-nullable and always defined.
  */
-export const requiredInteger = ({ initial = 0, min = 0, max, label } = {}) => new NumberField({ initial, label, min, max, required: true, nullable: false, integer: true });
+export const requiredInteger = ({ initial = 0, min = 0, max, label, persisted } = {}) => new NumberField({ initial, label, min, max, persisted, required: true, nullable: false, integer: true });
```
Comment (krbz999) [inline src/module/data/helpers.mjs:13]: How much effort is this method really saving? Data fields are entered just once in the code, and we will never - barring this one instance - want to make a change to number fields that should affect all of them.

**Review by krbz999 — APPROVED** [review]
A few comments related to some changes that weren't to do with the `persisted` property.

In addition, a large PR like this with broad sweeping changes was difficult to review. So I am going to have to trust that proper testing was done. I would have felt more confident reviewing smaller PRs targeted at specific models.

File: src/module/data/helpers.mjs (hunk 3 above)
Comment (JPMeehan) [reply src/module/data/helpers.mjs:13]: We use it a decent amount, mostly just wanted a standardized way of required: true, nullable false with numbers that felt more readable. Very open to just replacing all of them.
