### PR TITLE
[#1692] Refactored message parts to improve usage of visibility options.

### LINKED ISSUE #1692: All abilities ( Main action , Maneuver Maliace abilities) are visible irrespectible to the private roll settings in 0.10
### What happened?

As stated above since 0.10 , all abilities when triggerd are displayed to every player even when set as a private, blind gm, self roll 
Image

Additionally even before 0.10 since maliace abilities don't have a roll in them,m there was no way to trigger them, as a private, blind gm, self roll and they were sent straight to chat for all the players to see

Image

### Reproduction Steps

> open a npc character sheet
> go to abilities , and for example Main action, slick any main action ability
> set the roll as a private, blind gm or self roll
> even though the colour in the chat indicates a blind roll the message will be displayed in it's entirety to players

### What core and system version are you reporting this for?

FVTT 13 Draw steel 0.10.1

### Bug Checklist

- [x] The issue occurs while all Modules are disabled
- [ ] I am using The Forge for hosting

### PR DESCRIPTION
**Pull request by JPMeehan**
I went with a general "favor hiding information if a message is marked as private" approach. I think #1693 is something we could explore after v14 with its refactor of the message visibility options.

### CODE REVIEW

File: src/module/data/pseudo-documents/message-parts/base-message-part.mjs [hunk 1]
```diff
@@ -89,6 +89,18 @@ export default class BaseMessagePart extends TypedPseudoDocument {
...
   /* -------------------------------------------------- */
 
+  /**
+   * Are inner pieces of this part visible to players?
+   * @type {boolean}
+   */
+  get isContentVisible() {
+    const whisper = this.message.whisper || [];
+    if (whisper.length) return whisper.includes(game.user.id) || (this.message.isAuthor && !this.message.blind);
+    return true;
```
Comment (krbz999) [inline src/module/data/pseudo-documents/message-parts/base-message-part.mjs]:
```suggestion
    const { whisper, isAuthor, blind } = this.message;
    if (whisper?.length) return whisper.includes(game.user.id) || (isAuthor && !blind);
    return true;
```

**Review by krbz999 — APPROVED** [review]
