### PR TITLE
Various 13.340 fixes

### LINKED ISSUE #387: Make adjustments for embedded/nested fields in 13.340
13.340 looks like it may have addressed some of the bugs around LOCALIZATION_PREFIXES, we should see if we can reduce our special casing.

### LINKED ISSUE #406: `DrawSteelTokenRuler#_getWaypointLabelContext` fixes
- `waypoint` is not writeable: `DeepReadonly<TokenRulerWaypoint>`. Use `state` instead.
- `waypoint.previous` might not be the last waypoint that got a label: so the skipped waypoints need to be accumulated (`state.segmentWaypoints`).

```js
  /**
   * @param {DeepReadonly<TokenRulerWaypoint>} waypoint
   * @param {object} state
   * @inheritdoc
   */
  _getWaypointLabelContext(waypoint, state) {
    const context = super._getWaypointLabelContext(waypoint, state);

    if (!this.token.inCombat) return context;

    state.segmentWaypoints ??= [];
    state.segmentWaypoints.push(waypoint);

    if ( !context ) return;

    const points = this.token.document.getCompleteMovementPath(state.segmentWaypoints);

    const startedNear = state.endPointEnemies ?? new Set();
    const endPointEnemies = new Set(this.token.document.getHostileTokensFromPoints([points.at(-1)]));
    const passedBy = new Set(this.token.document.getHostileTokensFromPoints(points)).union(startedNear);
    const delta = waypoint.actionConfig.teleport ? 0 : passedBy.difference(endPointEnemies).size;
    const strikes = {
      delta,
      total: delta + (state.strikes?.total ?? 0),
    };

    state.endPointEnemies = endPointEnemies;
    state.strikes = strikes;
    state.segmentWaypoints = [waypoint];
    context.strikes = strikes;

    return context;
  }
```

This code hasn't been tested.

### PR DESCRIPTION
**Pull request by JPMeehan**
- Took another look at how data fields are handled; while the localization loops may be messy, it's better than the alternatives to repetition
  - Fixed new bug in actor data prep related to field path changes (Closes #387)
- Made token ruler adjustments to canSelect logic for prototype token
- Reworked token ruler context prep again (Closes #406)
- Added a tooltip for gaining surges via spending hero tokens on the character sheet

### CODE REVIEW

File: src/module/canvas/placeables/tokens/token-ruler.mjs [hunk 1]
```diff
@@ -29,66 +30,82 @@ export default class DrawSteelTokenRuler extends foundry.canvas.placeables.token
...
 
   /* -------------------------------------------------- */
 
   /**
-   * @param {TokenRulerWaypoint} waypoint
-   * @param {object} state
-   * @inheritdoc */
+   * @typedef WaypointLabelState
+   * @property {TokenRulerWaypoint[]} segmentWaypoints
+   * @property  {Set<DrawSteelTokenDocument>} endPointEnemies
```
Comment (krbz999) [inline src/module/canvas/placeables/tokens/token-ruler.mjs:73]:
```suggestion
   * @property {Set<DrawSteelTokenDocument>} endPointEnemies
```

**Review by krbz999 — APPROVED** [review]
