### PR TITLE
Token Ruler Fixes

### LINKED ISSUE #392: Check strike disposition handling
Might be friendly fire issues.

### LINKED ISSUE #396: Fix token ruler for 13.340
https://github.com/foundryvtt/foundryvtt/issues/12542

https://github.com/foundryvtt/foundryvtt/issues/12393

https://github.com/foundryvtt/foundryvtt/issues/12543

### PR DESCRIPTION
**Pull request by JPMeehan**
Closes #396 

Closes #392

### CODE REVIEW

File: src/module/config.mjs [hunk 1]
```diff
@@ -86,61 +85,11 @@ DRAW_STEEL.sizes = {
...
-    speedOption: true,
-  },
-  walk: {
-    label: "TOKEN.MOVEMENT.ACTIONS.walk.label",
-    icon: "fa-solid fa-fw fa-person-walking",
-    speedOption: true,
-  },
-};
-// Not prelocalizing because expectation is waypoint template will do so
+DRAW_STEEL.speedOptions = ["teleport", "fly", "walk", "swim", "burrow", "climb"];
```
Comment (krbz999) [inline src/module/config.mjs:92]: Are we totally sure we do not want this to be an object? Ime, all config entries have always sooner or later needed to have additional values.

File: tools/create-symlinks.mjs [hunk 2]
```diff
@@ -27,7 +27,7 @@ if (fs.existsSync("foundry-config.yaml")) {
   }
 
   // Javascript files
-  for (const p of ["client", "common"]) {
+  for (const p of ["client", "common", "tsconfig.json"]) {
```
Comment (krbz999) [inline tools/create-symlinks.mjs:30]: \*makes note\*

**Review by krbz999 — APPROVED** [review]
Red > green make brain happy.
